### PR TITLE
For #4 Support custom user models

### PR DESCRIPTION
**Pull request by sigshen**

### CODE REVIEW

**Comment by stevejalim** [comment]
LGTM

**Comment by hugorodgerbrown** [comment]
HI @sigshen thanks for the PR. Could you add a test in with a custom user model just to confirm it all works. (https://github.com/sigshen/django-request-profiler/blob/master/request_profiler/tests.py#L132)

**Comment by sigshen** [comment]
No problem!

**Comment by sigshen** [comment]
Done, please review, thanks :)

**Comment by hugorodgerbrown** [comment]
HI @sigshen - unfortunately the build failed - you can take a look at the output here - https://travis-ci.org/yunojuno/django-request-profiler/builds/80976125

**Comment by hugorodgerbrown** [comment]
Looking at this again - the issue is that the latest master has been update to accomodate Django 1.4, 1.5, which obviously do not support custom user models. Will need some work to get them all to play nicely.

**Comment by hugorodgerbrown** [comment]
I'm afraid this is my fault - without really thinking about it I accepted what are essentially mutually-exclusive requirements - a.) support for old Django versions, which don't have custom user models, and b.) support for custom user models.

Supporting new versions of Django is much more important - so will try and untangle this over the weekend if I get a chance.

**Comment by sigshen** [comment]
I think it's worth to upgrade Django versions to 1.7, 1.8 (Django 1.8 has been designated as Django’s second “Long-Term Support” (LTS) release).

Actually, i am currently developing a project using Django  1.8 : )

**Comment by stevejalim** [comment]
@hugorodgerbrown Maybe we remove the changes from the legacy-support PR and instead turn them into a standalone feature branch as legacy-support-if-you-need-it, then merge this custom user PR into master.

**Comment by hugorodgerbrown** [comment]
I've done something similar - I've tagged django_1.5 and django_1.4 and then removed them, and merged in @sigshen's PR. (As well as added tox environment for 1.8). It's a mess (in repo terms), but we're back on track, and this should work. I've pushed the latest version tp PyPI as 0.9

**Pull request merged**
